/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sstone_vsockj_VSock */

#ifndef _Included_com_github_sstone_vsockj_VSock
#define _Included_com_github_sstone_vsockj_VSock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_sstone_vsockj_VSock
 * Method:    open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_sstone_vsockj_VSock_open
  (JNIEnv *, jclass);

/*
 * Class:     com_github_sstone_vsockj_VSock
 * Method:    connect
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_com_github_sstone_vsockj_VSock_connect
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_github_sstone_vsockj_VSock
 * Method:    send
 * Signature: (J[BII)J
 */
JNIEXPORT jlong JNICALL Java_com_github_sstone_vsockj_VSock_send
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_github_sstone_vsockj_VSock
 * Method:    receive
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_sstone_vsockj_VSock_receive
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
